import type { AthleteProfile } from "./mock-data";

export const athletes: AthleteProfile[] = [
  {
    id: "mcmorris",
    name: "Mark McMorris",
    name_en: "マーク・マクモリス",
    nationality: "Canada",
    birthplace: "Regina, Saskatchewan",
    birth_date: "December 9, 1993",
    age: 32,
    sport: "Snowboard",
    family: "Father (provincial legislator), mother (nurse), brother Craig (pro snowboarder)",
    upbringing: "Grew up on the flat prairies with no mountains in sight. He turned the small ledge in his backyard into a makeshift jump, honing a self-taught style while competing against his older brother.",
    main_quote: "Just being able to ride makes me happy. Medals are just a bonus.",
    sub_quote: "Every time I could move my finger even a millimeter, I celebrated with everything I had. Celebrating small victories is what leads to a great comeback.",
    achievements: ["Bronze medal at three consecutive Olympics: 2014, 2018, 2022", "11 X Games gold medals"],
    injury_detail: "In 2017, he crashed into a tree after a failed backcountry jump landing in Whistler. He suffered 17 fractures (jaw, left arm, pelvis, ribs, etc.), a collapsed lung, and a ruptured spleen, leaving him in a coma.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "hirano",
    name: "Ayumu Hirano",
    name_en: "平野 歩夢",
    nationality: "Japan",
    birthplace: "Murakami, Niigata Prefecture",
    birth_date: "November 29, 1998",
    age: 27,
    sport: "Snowboard",
    family: "Father (Hideki), mother (Fumiko), older brother Eiki and younger brother Kaishu (both pro snowboarders). Wife and child.",
    upbringing: "Trained relentlessly from childhood at a Sea of Japan skate park built by his father. His father's coaching philosophy of 'not tolerating even a millimeter of error' became the foundation of his precision technique.",
    main_quote: "I walk through my dreams. The name my mother gave me became the way I live.",
    sub_quote: "Fear never goes away. But that fear makes me more careful and stronger.",
    achievements: ["2022 Beijing Olympics gold medal", "2014 & 2018 Olympic silver medals"],
    injury_detail: "In March 2017, he struck the deck of a halfpipe and ruptured his liver. In January 2026, he fractured his pelvis (ilium) just before the Milan Olympics.",
    image_url: null,
    comeback_status: "in_progress",
  },
  {
    id: "okamoto",
    name: "Keiji Okamoto",
    name_en: "岡本 圭司",
    nationality: "Japan",
    birthplace: "Miki, Hyogo Prefecture",
    birth_date: "February 20, 1982",
    age: 43,
    sport: "Para Snowboard",
    family: "Wife and children.",
    upbringing: "One of Japan's top professional snowboarders, passionately dedicated to film production and pioneering new terrain.",
    main_quote: "Rather than counting what I've lost, it's more fun to think about what I can do with what I still have.",
    sub_quote: "Getting injured doesn't make you unlucky. It's how you shape your life afterward that gives it meaning.",
    achievements: ["2007 X-TRAIL JAM highest-placing Japanese rider", "2022 Beijing Paralympics 8th place"],
    injury_detail: "In 2015, he fell from a cliff during a filming session. He slammed into concrete, suffering 15 fractures across his body, spinal cord damage, and paralysis below the right knee.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "ohtani",
    name: "Shohei Ohtani",
    name_en: "大谷 翔平",
    nationality: "Japan",
    birthplace: "Oshu, Iwate Prefecture",
    birth_date: "July 5, 1994",
    age: 31,
    sport: "Baseball",
    family: "Father (corporate league baseball player), mother (badminton player), older brother, older sister.",
    upbringing: "Raised amid the rich nature of Iwate, he obsessively self-analyzed through a 'baseball notebook.' From middle school, he used a goal-achievement chart (Mandala Chart) to visualize his dreams.",
    main_quote: "I see rehab as time to upgrade myself.",
    sub_quote: "Because I got injured, I was able to think about how to use my body more efficiently than before.",
    achievements: ["2021 & 2023 MLB MVP", "2023 Home Run King, WBC Champion"],
    injury_detail: "Torn UCL (ulnar collateral ligament) in his right elbow. Underwent surgery twice — in 2018 and 2023 (Tommy John surgery, among others).",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "murray",
    name: "Andy Murray",
    name_en: "アンディ・マレー",
    nationality: "United Kingdom",
    birthplace: "Scotland",
    birth_date: "May 15, 1987",
    age: 38,
    sport: "Tennis",
    family: "Mother (tennis coach), brother (former world No. 1 doubles), wife, four children.",
    upbringing: "Under his mother's coaching, he developed a tenacious playing style in the harsh Scottish climate.",
    main_quote: "Being able to play the sport I love without pain — that alone makes me a winner.",
    sub_quote: "They told me I'd never play professional tennis again. But my heart was screaming, 'It's not over yet.'",
    achievements: ["Two-time Wimbledon champion", "Back-to-back Olympic gold medals, former world No. 1"],
    injury_detail: "Osteoarthritis of the hip. He endured years of excruciating pain so severe that even putting on socks was a struggle.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "kunieda",
    name: "Shingo Kunieda",
    name_en: "国枝 慎吾",
    nationality: "Japan",
    birthplace: "Kashiwa, Chiba Prefecture",
    birth_date: "February 21, 1984",
    age: 41,
    sport: "Wheelchair Tennis",
    family: "Wife (Ai), parents.",
    upbringing: "Confined to a wheelchair at age 9. At his mother's encouragement, he took up tennis and mastered chairwork — maneuvering his wheelchair as if it were an extension of his own legs.",
    main_quote: "I am the strongest!",
    sub_quote: "It's always your own mind that sets your limits. My wheelchair is my legs — and my wings.",
    achievements: ["Three Paralympic gold medals, career Golden Slam", "People's Honor Award"],
    injury_detail: "Spinal cord tumor at age 9. In 2016, severe pain from loose cartilage fragments (joint mice) in his right elbow.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "ikee",
    name: "Rikako Ikee",
    name_en: "池江 璃花子",
    nationality: "Japan",
    birthplace: "Tokyo",
    birth_date: "July 4, 2000",
    age: 25,
    sport: "Swimming",
    family: "Mother, older sister, older brother.",
    upbringing: "Guided by a mother skilled in early childhood education, she developed exceptional physical balance from a young age through activities like monkey bars.",
    main_quote: "Adversity doesn't visit those who can't overcome it. God only gives trials to those strong enough to endure them.",
    sub_quote: "In my hardest moments, someone was always there to support me. That's the greatest happiness of all.",
    achievements: ["2018 Asian Games — six gold medals", "2021 Japan Championships — four titles, 2024 Paris Olympics qualifier"],
    injury_detail: "Diagnosed with acute lymphoblastic leukemia in 2019.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "woods",
    name: "Tiger Woods",
    name_en: "タイガー・ウッズ",
    nationality: "United States",
    birthplace: "California",
    birth_date: "December 30, 1975",
    age: 50,
    sport: "Golf",
    family: "Father (the late Earl), mother, daughter (Sam), son (Charlie).",
    upbringing: "Received a steel-forged mental education from his military father — lessons that applied far beyond the golf course.",
    main_quote: "I wanted to play with my son again. That wish is what got me back on my feet.",
    sub_quote: "The pain may never go away. But how you accept it and how you control it — that's golf.",
    achievements: ["15 major championships", "2019 Masters — the comeback victory"],
    injury_detail: "In 2021, a car accident left him with a shattered right leg and the threat of amputation.",
    image_url: null,
    comeback_status: "completed_partial",
  },
  {
    id: "mitoma",
    name: "Kaoru Mitoma",
    name_en: "三笘 薫",
    nationality: "Japan",
    birthplace: "Kawasaki, Kanagawa Prefecture",
    birth_date: "May 20, 1997",
    age: 28,
    sport: "Soccer/Football",
    family: "Father, mother, older brother, wife.",
    upbringing: "Grew up through Kawasaki Frontale's academy. A true tactician, he wrote his university thesis scientifically analyzing dribbling techniques.",
    main_quote: "I saw my injury as a gift — a chance to objectively analyze my own play.",
    sub_quote: "Giving up was never an option in my dictionary to begin with.",
    achievements: ["2022 World Cup — 'Mitoma's 1mm' goal-line moment", "Most goals by a Japanese player in the Premier League"],
    injury_detail: "In 2024, suffered a lumbar spine injury.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "abe",
    name: "Hifumi Abe",
    name_en: "阿部 一二三",
    nationality: "Japan",
    birthplace: "Kobe, Hyogo Prefecture",
    birth_date: "August 9, 1997",
    age: 28,
    sport: "Judo",
    family: "Father (firefighter), mother, older brother, younger sister (Uta).",
    upbringing: "Competed against his younger sister Uta from childhood, relentlessly pursuing attacking judo. His father's training built his powerful lower body.",
    main_quote: "Having the courage to take a step back gives you the strength to take two steps forward.",
    sub_quote: "Who you are after a loss — that's where your true character shows.",
    achievements: ["2021 & 2024 Olympic gold medal in 66kg (back-to-back titles)"],
    injury_detail: "Finger injuries and the intense pressure of national team selection.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "kimura",
    name: "Keiichi Kimura",
    name_en: "木村 敬一",
    nationality: "Japan",
    birthplace: "Ritto, Shiga Prefecture",
    birth_date: "September 11, 1990",
    age: 35,
    sport: "Para Swimming",
    family: "Parents.",
    upbringing: "Lost his sight at age 2. His mother's philosophy of 'let him try everything' led him to swimming, where he turned his heightened sense of touch into a weapon.",
    main_quote: "Because I can't see, my other senses are sharpened. That's a privilege only I have.",
    sub_quote: "The years I couldn't win gold taught me the true value of teammates.",
    achievements: ["2021 & 2024 Tokyo & Paris Paralympic gold medals"],
    injury_detail: "Total blindness. The devastation of winning zero gold medals at the 2016 Rio Paralympics.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "sanibrawn",
    name: "Abdul Hakim Sani Brown",
    name_en: "サニブラウン・アブデル・ハキーム",
    nationality: "Japan",
    birthplace: "Tokyo",
    birth_date: "March 6, 1999",
    age: 26,
    sport: "Track & Field",
    family: "Ghanaian father, Japanese mother, younger brother.",
    upbringing: "Experienced both soccer and track & field as a dual-sport athlete. His world-class physique fused with Japanese-style discipline.",
    main_quote: "The time I spent injured was a research period — a dialogue with my own body.",
    sub_quote: "There's no need to rush back. When you return to 100%, the results will follow.",
    achievements: ["2022 & 2023 World Championships — consecutive 100m finals", "2024 Paris Olympics — 9.96 seconds"],
    injury_detail: "2020–21: lumbar spondylolysis and hamstring injuries.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "ito",
    name: "Mima Ito",
    name_en: "伊藤 美誠",
    nationality: "Japan",
    birthplace: "Iwata, Shizuoka Prefecture",
    birth_date: "October 21, 2000",
    age: 25,
    sport: "Table Tennis",
    family: "Mother (Minori).",
    upbringing: "Raised under her mother's intensive training. She practiced her unique serves relentlessly, often late into the night.",
    main_quote: "The frustration of losing becomes the greatest investment for winning the next match.",
    sub_quote: "I don't care what anyone else says. I just keep walking my own path.",
    achievements: ["2021 Tokyo Olympics mixed doubles gold medal"],
    injury_detail: "Lower back pain, and the psychological blow of failing to qualify for the 2024 Paris Olympics team.",
    image_url: null,
    comeback_status: "in_progress",
  },
  {
    id: "toratani",
    name: "Mao Toratani",
    name_en: "虎谷 真央",
    nationality: "Japan",
    birthplace: "Kyoto Prefecture",
    birth_date: "c. 2000",
    age: 25,
    sport: "Wheelchair Fencing",
    family: "Parents.",
    upbringing: "A promising kendo and fencing prospect with exceptional physical ability before his accident.",
    main_quote: "When I hold a sword, it doesn't matter that my legs don't work. In that world, I'm free.",
    sub_quote: "I exist now to surpass the person I used to be.",
    achievements: ["2024 Paris Paralympics competitor"],
    injury_detail: "Spinal cord injury from an accident.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "durant",
    name: "Kevin Durant",
    name_en: "ケビン・デュラント",
    nationality: "United States",
    birthplace: "Washington, D.C.",
    birth_date: "September 29, 1988",
    age: 37,
    sport: "Basketball",
    family: "Mother (Wanda), older brother. His mother was so devoted to raising him that she was hailed as 'The Real MVP.'",
    upbringing: "Growing up in a low-income household, he channeled his mother's encouragement into a basketball obsession. Despite his towering height, he developed guard-like skills.",
    main_quote: "Hard work beats talent when talent doesn't work hard.",
    sub_quote: "When I tore my Achilles, I saw it as a chance to rebuild myself from scratch.",
    achievements: ["2017 & 2018 NBA Champion & Finals MVP", "2012, 2016, 2021, & 2024 Olympic gold medals"],
    injury_detail: "During the 2019 NBA Finals, he ruptured his right Achilles tendon — an injury often considered a career death sentence for basketball players.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "takahashi_ran",
    name: "Ran Takahashi",
    name_en: "高橋 藍",
    nationality: "Japan",
    birthplace: "Kyoto Prefecture",
    birth_date: "September 2, 2001",
    age: 24,
    sport: "Volleyball",
    family: "Father, mother, older brother (Rui, volleyball player), younger sister.",
    upbringing: "Inspired by his older brother to start volleyball, he pursued a dual-threat style combining elite defense as a libero with offensive power.",
    main_quote: "The time I can't stand on the court is time to see volleyball more objectively than anyone else.",
    sub_quote: "I think of setbacks as a wind-up — stored energy for coming back stronger.",
    achievements: ["2024 Nations League silver medal", "Standout career in Italy's Serie A"],
    injury_detail: "In 2024, suffered an ankle injury during a critical league stretch. A major source of anxiety heading into the Olympics.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "leitch",
    name: "Michael Leitch",
    name_en: "リーチ マイケル",
    nationality: "Japan (born in New Zealand)",
    birthplace: "Sapporo (from high school onward)",
    birth_date: "October 7, 1988",
    age: 37,
    sport: "Rugby",
    family: "Wife and children.",
    upbringing: "Came to Japan at 15 as an exchange student. He immersed himself in Japanese culture, developing a deep sense of responsibility and leadership.",
    main_quote: "A crisis is a chance to test our bond. If you don't run away, a path will always open.",
    sub_quote: "When injury keeps me off the field, that's when I think hardest about what I can do for the team.",
    achievements: ["Japan national team captain at 2015 & 2019 Rugby World Cups", "Three consecutive World Cup appearances"],
    injury_detail: "Just before the 2019 World Cup, he suffered hip and knee injuries. He could barely walk as the tournament approached.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "irie",
    name: "Sena Irie",
    name_en: "入江 聖奈",
    nationality: "Japan",
    birthplace: "Yonago, Tottori Prefecture",
    birth_date: "October 9, 2000",
    age: 25,
    sport: "Boxing",
    family: "Father, mother.",
    upbringing: "Inspired by the manga 'Ganbare Genki' to take up boxing. Known for her unique love of frogs and a personality that thrives on disciplined, repetitive training.",
    main_quote: "I have no natural talent. That's exactly why the only way I can feel secure is by training harder than everyone else.",
    sub_quote: "The frustration of losing is the finest ingredient for the next victory.",
    achievements: ["2021 Tokyo Olympics featherweight gold medal"],
    injury_detail: "A deep slump during the national team selection period. A string of losses drove her to the brink of retirement — a profound psychological crisis.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "kasai",
    name: "Noriaki Kasai",
    name_en: "葛西 紀明",
    nationality: "Japan",
    birthplace: "Shimokawa, Hokkaido",
    birth_date: "June 6, 1972",
    age: 53,
    sport: "Ski Jumping",
    family: "Wife, children, late sister.",
    upbringing: "Raised in the bitter cold of Shimokawa, he built an indomitable spirit that defied adversity. He overcame many personal hardships, including his sister's illness and family deaths.",
    main_quote: "Hard work never betrays you. If you feel betrayed, you simply haven't worked hard enough.",
    sub_quote: "My real jumping career didn't begin until after I turned 40.",
    achievements: ["Eight consecutive Olympic appearances (Guinness World Record)", "2014 Sochi Olympics individual silver medal"],
    injury_detail: "A major knee injury in his early career. Years of poor results followed. Throughout his 30s, he was widely dismissed as a 'washed-up' athlete.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "tanaka",
    name: "Masahiro Tanaka",
    name_en: "田中 将大",
    nationality: "Japan",
    birthplace: "Itami, Hyogo Prefecture",
    birth_date: "November 1, 1988",
    age: 37,
    sport: "Baseball",
    family: "Wife (Mai Satoda), children.",
    upbringing: "Won back-to-back national high school championships at Komazawa University Tomakomai High. He established himself as a winning pitcher at a young age.",
    main_quote: "When it comes to obsessing over every single pitch, I refuse to lose to anyone.",
    sub_quote: "My elbow injury taught me how to pitch with finesse instead of brute force.",
    achievements: ["2013 — 24 consecutive wins without a loss", "Stellar MLB career, WBC champion"],
    injury_detail: "In 2014, a partial tear of his right elbow ligament. A condition that would normally require Tommy John surgery.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "ishikawa",
    name: "Yuki Ishikawa",
    name_en: "石川 祐希",
    nationality: "Japan",
    birthplace: "Okazaki, Aichi Prefecture",
    birth_date: "December 11, 1995",
    age: 30,
    sport: "Volleyball",
    family: "Father, mother, younger sister (Mayu, volleyball player).",
    upbringing: "Both his older and younger sisters played volleyball. He reached the national pinnacle in middle school and moved early to Italy's league to sharpen his individual skill.",
    main_quote: "If you want to be the best in the world, you need to put yourself in the toughest environment in the world.",
    sub_quote: "While I was sidelined with injury, I spiked the ball a hundred times in my mind every day.",
    achievements: ["2024 Nations League silver medal", "MVP-caliber performances in Italy's Serie A"],
    injury_detail: "In 2023, worsening back pain and lower-body injuries during the season. The pressure of being national team captain compounded the situation.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "yamamoto",
    name: "Yoshinobu Yamamoto",
    name_en: "山本 由伸",
    nationality: "Japan",
    birthplace: "Bizen, Okayama Prefecture",
    birth_date: "August 17, 1998",
    age: 27,
    sport: "Baseball",
    family: "Father, mother.",
    upbringing: "A virtual unknown in high school, he pushed his physical abilities to the limit through unconventional training methods like bridge exercises and javelin throwing.",
    main_quote: "True strength comes from questioning conventional wisdom.",
    sub_quote: "I treated the time I couldn't pitch as the perfect investment period — letting my arm rest and recharge.",
    achievements: ["First pitcher in NPB history to win five pitching titles three years straight & Sawamura Award", "2024 World Series champion"],
    injury_detail: "In 2024, during his first year with the Dodgers, he was sidelined long-term with a right shoulder injury (triceps strain).",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "fukuhara",
    name: "Ai Fukuhara",
    name_en: "福原 愛",
    nationality: "Japan",
    birthplace: "Sendai, Miyagi Prefecture",
    birth_date: "November 1, 1988",
    age: 37,
    sport: "Table Tennis",
    family: "Father, mother, older brother.",
    upbringing: "Known as a 'table tennis prodigy' since age 3. She built her grit by never quitting practice — even through tears — and developed the mental fortitude to carry an entire nation's expectations.",
    main_quote: "Even if you lose, if you take something from it, it's not really a loss.",
    sub_quote: "When injury kept me from holding a racket, I started playing with my left hand. There's always something you can do.",
    achievements: ["2012 & 2016 Olympic team medals", "All Japan Championship winner"],
    injury_detail: "In 2014, fractured her left big toe. Additionally, years of chronic pain in her right elbow and right shoulder.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "inoue",
    name: "Naoya Inoue",
    name_en: "井上 尚弥",
    nationality: "Japan",
    birthplace: "Zama, Kanagawa Prefecture",
    birth_date: "April 10, 1993",
    age: 32,
    sport: "Boxing",
    family: "Father (Shingo), younger brother (Takuma), younger sister, wife, children.",
    upbringing: "Under his father's coaching, he repeated the fundamentals tens of thousands of times. That uncompromising training environment forged 'The Monster.'",
    main_quote: "Only an overwhelming volume of training can erase fear inside the ring.",
    sub_quote: "When I fractured my orbital bone and everything looked double, I told myself, 'If one eye still works, I can still win.'",
    achievements: ["World champion in four weight classes", "Undisputed champion in two weight classes (first in history)", "Pound-for-pound No. 1"],
    injury_detail: "During his 2019 fight against Nonito Donaire, he suffered an orbital floor fracture and broken nose. He was seeing double in the middle of the bout — a desperate situation.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "kunieda_v2",
    name: "Shingo Kunieda",
    name_en: "国枝 慎吾",
    nationality: "Japan",
    birthplace: "Kashiwa, Chiba Prefecture",
    birth_date: "February 21, 1984",
    age: 41,
    sport: "Wheelchair Tennis",
    family: "Wife (Ai), parents.",
    upbringing: "Confined to a wheelchair at age 9. At his mother's encouragement, he took up tennis and mastered chairwork — maneuvering his wheelchair as if it were an extension of his own legs.",
    main_quote: "My wheelchair is my 'legs.' How I command it defines my tennis.",
    sub_quote: "When I kept losing because of injury, I finally admitted my weakness — and that's when I became truly strong.",
    achievements: ["2021 Tokyo Paralympics gold medal", "50 Grand Slam titles"],
    injury_detail: "Right elbow surgery just before the 2016 Rio Paralympics. Afterward, he fell into a near-yips state from pain, and his world ranking plummeted.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "kimura_v2",
    name: "Keiichi Kimura",
    name_en: "木村 敬一",
    nationality: "Japan",
    birthplace: "Shiga Prefecture",
    birth_date: "September 11, 1990",
    age: 35,
    sport: "Para Swimming",
    family: "Parents.",
    upbringing: "Lost his sight at age 2. His mother's philosophy of 'let him try everything' led him to swimming, where he turned his heightened sense of touch into a weapon.",
    main_quote: "I want to measure happiness by my own yardstick, not someone else's.",
    sub_quote: "When I settled for silver in Rio, that was the first time I truly felt, 'Nothing but gold will do.'",
    achievements: ["2021 & 2024 gold medals"],
    injury_detail: "Non-congenital blindness (lost sight at age 2). The psychological defeat of winning four medals at Rio 2016 but none of them gold.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "tani",
    name: "Mami Tani",
    name_en: "谷 真海",
    nationality: "Japan",
    birthplace: "Kesennuma, Miyagi Prefecture",
    birth_date: "March 12, 1982",
    age: 43,
    sport: "Para Triathlon / Para Athletics",
    family: "Husband, children, parents.",
    upbringing: "Diagnosed with osteosarcoma while a cheerleader at Waseda University. Naturally energetic, she had always expressed herself through sport.",
    main_quote: "Instead of counting what I've lost, I want to maximize the possibilities that remain.",
    sub_quote: "When the tsunami washed away my hometown, I became certain: as long as you're alive, you can do anything.",
    achievements: ["Moved the world with her speech during the Olympic bid presentation", "2021 Tokyo Paralympics competitor"],
    injury_detail: "In 2002, her right foot was amputated below the ankle due to osteosarcoma. Then in 2011, the Great East Japan Earthquake devastated her family home.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "murata",
    name: "Choji Murata",
    name_en: "村田 兆治",
    nationality: "Japan",
    birthplace: "Toyota District, Hiroshima Prefecture",
    birth_date: "November 27, 1949",
    age: 72,
    sport: "Baseball",
    family: "Wife (Yoshiko), children.",
    upbringing: "Raised on an island off Hiroshima, he learned perseverance from his fisherman father. He became an ace with his trademark 'Masakari' (battle-axe) pitching motion.",
    main_quote: "Life is a complete game. I want to stay on my own two feet until the very end.",
    sub_quote: "They said surgery meant retirement. Fine — then I'd write a new chapter of history.",
    achievements: ["215 career wins", "1985 comeback season — 17 wins", "Inducted into the Meikyukai (Golden Players Club)"],
    injury_detail: "In 1982, a devastating injury to his right elbow. At the time, the conventional wisdom was that surgery meant the end of a career.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "watanabe",
    name: "Yuta Watanabe",
    name_en: "渡邊 雄太",
    nationality: "Japan",
    birthplace: "Miki, Kagawa Prefecture",
    birth_date: "October 13, 1994",
    age: 31,
    sport: "Basketball",
    family: "Father (former player), mother (former player), older sister, wife (Akiko Kuji).",
    upbringing: "Born into a basketball family, he was determined from childhood to leave Japan and become a player who could compete on the world stage.",
    main_quote: "If you don't have talent, you have to be the first one in the gym and the last one to leave.",
    sub_quote: "The times I can't step on the court are precious moments to confront my inner self.",
    achievements: ["Second Japanese player to sign an NBA contract", "Six NBA seasons", "Key contributor to Japan's FIBA World Cup breakthrough"],
    injury_detail: "Repeated hamstring and ankle injuries throughout his NBA career. The constant struggle of maintaining peak condition amid fierce competition.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "akiyama",
    name: "Shogo Akiyama",
    name_en: "秋山 翔吾",
    nationality: "Japan",
    birthplace: "Yokosuka, Kanagawa Prefecture",
    birth_date: "April 16, 1988",
    age: 37,
    sport: "Baseball",
    family: "Wife, children.",
    upbringing: "Lost his father at a young age and was raised by his mother alone. Honoring a promise made to his father, he swung a bat more than anyone to become a professional baseball player.",
    main_quote: "Preparation is everything. Results are just the answer sheet of your preparation.",
    sub_quote: "Having been through near-release taught me the weight of every single day I get to play baseball.",
    achievements: ["216 hits in a single season (Japanese record)", "MLB career", "Successful return to NPB"],
    injury_detail: "Foot injuries and a drastic loss of playing time during his MLB tenure. In 2022, he was effectively released by the Padres.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "uchimura",
    name: "Kohei Uchimura",
    name_en: "内村 航平",
    nationality: "Japan",
    birthplace: "Kitakyushu, Fukuoka Prefecture (raised in Nagasaki)",
    birth_date: "January 3, 1989",
    age: 37,
    sport: "Gymnastics",
    family: "Parents (both gymnastics coaches), younger sister. Wife, children.",
    upbringing: "The trampoline at his parents' sports club was his playground. His aerial awareness was nurtured through play, laying the groundwork for his pursuit of 'the art of the perfect landing.'",
    main_quote: "I'm no genius. I just practiced more and thought about gymnastics more than anyone else.",
    sub_quote: "The pain in both shoulders taught me the ultimate efficiency — how to perform without relying on brute strength.",
    achievements: ["Two consecutive Olympic all-around gold medals", "Six consecutive World Championship all-around titles"],
    injury_detail: "Chronic injuries to both shoulders and torn ankle ligaments. By the time of the Tokyo Olympics, he was so worn down that he had to abandon the all-around and focus solely on the horizontal bar.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "tomita",
    name: "Uchu Tomita",
    name_en: "富田 宇宙",
    nationality: "Japan",
    birthplace: "Kumamoto, Kumamoto Prefecture",
    birth_date: "February 28, 1989",
    age: 36,
    sport: "Para Swimming",
    family: "Parents.",
    upbringing: "Passionate about swimming from childhood. Diagnosed with retinitis pigmentosa in high school, he continued competing while battling the terror of gradually losing his sight.",
    main_quote: "Despair is nothing more than a screen onto which a new version of yourself is projected.",
    sub_quote: "Because I lost my sight, water resistance and the movement of my muscles became clearer than vision ever was.",
    achievements: ["2021 Tokyo Paralympics silver & bronze medals", "2024 Paris Paralympics silver medal"],
    injury_detail: "A progressive visual impairment that eventually took all his sight. The devastating loss of his dream of competing at the highest level as an able-bodied athlete.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "sato_mami",
    name: "Mami Sato",
    name_en: "佐藤 真海",
    nationality: "Japan",
    birthplace: "Kesennuma, Miyagi Prefecture",
    birth_date: "March 12, 1982",
    age: 43,
    sport: "Para Athletics (Long Jump)",
    family: "Husband, children, parents.",
    upbringing: "Diagnosed with osteosarcoma while at Waseda University. She chose to rise from the despair of losing her right foot and devote her life to giving back through the power of sport.",
    main_quote: "Sport saved my life. That's why I want to give back through sport.",
    sub_quote: "I may have lost my leg, but my heart has wings.",
    achievements: ["Legendary speech during the Olympic bid", "World-class competitor in Para Athletics and Para Triathlon"],
    injury_detail: "Right foot amputated due to osteosarcoma. Compounded by the 2011 Great East Japan Earthquake, which destroyed her family home and took the lives of friends.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "zanardi",
    name: "Alex Zanardi",
    name_en: "アレックス・ザナルディ",
    nationality: "Italy",
    birthplace: "Bologna",
    birth_date: "October 23, 1966",
    age: 59,
    sport: "Motorsport / Handcycling",
    family: "Wife, son.",
    upbringing: "Obsessed with go-karts from childhood. His indomitable fighting spirit carried him all the way to Formula 1.",
    main_quote: "When I lost both legs, I thought, 'Great — now I get to find a new hobby: handcycling.'",
    sub_quote: "In life, there are only two choices: give up, or keep moving forward.",
    achievements: ["Two-time CART champion", "Four Paralympic gold medals"],
    injury_detail: "In 2001, he collided at 200 mph during a race in Germany. Both legs were amputated, and he lost 70% of his blood — he was on the brink of death.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "eriksen",
    name: "Christian Eriksen",
    name_en: "クリスチャン・エリクセン",
    nationality: "Denmark",
    birthplace: "Middelfart",
    birth_date: "February 14, 1992",
    age: 34,
    sport: "Soccer/Football",
    family: "Wife, children.",
    upbringing: "Technically gifted from childhood, he was hailed as Denmark's crown jewel — a maestro playmaker.",
    main_quote: "Just being able to step onto the pitch makes me feel alive.",
    sub_quote: "The day my heart stopped was simply my second birthday.",
    achievements: ["Major contributions in the Premier League and Serie A", "Playmaker of the Danish national team"],
    injury_detail: "During Euro 2020 in 2021, he suffered cardiac arrest and collapsed on the pitch. His life hung in the balance.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "yamasaki",
    name: "Yasuaki Yamasaki",
    name_en: "山崎 康晃",
    nationality: "Japan",
    birthplace: "Arakawa, Tokyo",
    birth_date: "October 2, 1992",
    age: 33,
    sport: "Baseball",
    family: "Mother (Vietnamese-born), older sister.",
    upbringing: "Raised single-handedly by his mother, he channeled his gratitude into a fierce hunger to succeed.",
    main_quote: "The mound is where I belong. I refuse to give it up to anyone.",
    sub_quote: "A slump is a gift — a reminder to go back to the basics.",
    achievements: ["Rookie of the Year", "Saves leader (twice), fan-favorite closer known for the 'Yasuaki Jump'"],
    injury_detail: "A prolonged slump around 2020. Hitters began reading his signature two-seam fastball, and he was demoted to the minors. Cruel voices declared him 'finished.'",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "hanyu",
    name: "Yuzuru Hanyu",
    name_en: "羽生 結弦",
    nationality: "Japan",
    birthplace: "Sendai, Miyagi Prefecture",
    birth_date: "December 7, 1994",
    age: 31,
    sport: "Figure Skating",
    family: "Parents, older sister.",
    upbringing: "Displaced by the Great East Japan Earthquake, he lived in an evacuation shelter. The gratitude of simply being able to skate was etched into his heart, fueling his fusion of artistry and technical mastery.",
    main_quote: "Hard work can lie to you. But those lies are never wasted.",
    sub_quote: "The more my right ankle hurt, the more I could set myself free.",
    achievements: ["Back-to-back Olympic gold medals", "Super Slam achieved"],
    injury_detail: "Countless ligament injuries to his right ankle. Before the PyeongChang Olympics, a major injury kept him off the ice for months.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "endo",
    name: "Wataru Endo",
    name_en: "遠藤 航",
    nationality: "Japan",
    birthplace: "Yokohama, Kanagawa Prefecture",
    birth_date: "February 9, 1993",
    age: 33,
    sport: "Soccer/Football",
    family: "Wife, four children.",
    upbringing: "He set his sights on playing abroad early on, keeping an analysis notebook to sharpen his strength in duels (one-on-one battles).",
    main_quote: "Preparation is everything. The match is decided before it even starts.",
    sub_quote: "The time I spent on the bench only made me tougher.",
    achievements: ["Bundesliga Duel King (twice)", "Transferred to Liverpool, captain of the Japan national team"],
    injury_detail: "A concussion just before the 2022 World Cup that put his participation in doubt. Additionally, an extended period on the bench at his club.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "ueno",
    name: "Yukiko Ueno",
    name_en: "上野 由岐子",
    nationality: "Japan",
    birthplace: "Fukuoka, Fukuoka Prefecture",
    birth_date: "July 22, 1982",
    age: 43,
    sport: "Softball",
    family: "Parents, younger sister.",
    upbringing: "Blessed with extraordinary arm strength from childhood, she became Japan's premier right-arm pitcher through the demanding training culture of Kyushu.",
    main_quote: "Limits are something you set for yourself. I can still evolve.",
    sub_quote: "The day I broke my jaw, my softball career was reset — and started all over again.",
    achievements: ["2008 & 2021 Olympic gold medals", "The legendary 413-pitch marathon"],
    injury_detail: "In 2019, a line drive struck her face during a game, causing a complex jaw fracture. A career-threatening injury.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "nishikori",
    name: "Kei Nishikori",
    name_en: "錦織 圭",
    nationality: "Japan",
    birthplace: "Matsue, Shimane Prefecture",
    birth_date: "December 29, 1989",
    age: 36,
    sport: "Tennis",
    family: "Parents, older sister, wife.",
    upbringing: "At 13, he left Japan to train at the Nick Bollettieri Academy in the U.S. He honed his footwork to overcome the physical disadvantage of his smaller frame.",
    main_quote: "Every time I come back from an injury, I rediscover the joy of playing tennis.",
    sub_quote: "During my time away, I fell even more in love with tennis. That alone made the comeback worthwhile.",
    achievements: ["US Open finalist", "Rio Olympics bronze medal"],
    injury_detail: "Wrist, hip, ankle, elbow — a career-long battle with injuries throughout his entire body. Extended absence from 2022 to 2023.",
    image_url: null,
    comeback_status: "completed_partial",
  },
  {
    id: "fujiwara",
    name: "Noriko Fujiwara",
    name_en: "藤原 紀子",
    nationality: "Japan",
    birthplace: "Various locations in Japan",
    birth_date: "Unknown",
    age: 35,
    sport: "Wheelchair Basketball",
    family: "Husband, children.",
    upbringing: "An active, sports-loving girl before a spinal cord injury from an accident changed her life.",
    main_quote: "My wheelchair is my 'cool fighter jet.'",
    sub_quote: "I thought my life was over once. Now I see every day as bonus time.",
    achievements: ["National team career", "Paralympic top-eight finish"],
    injury_detail: "Lower-body paralysis caused by a traffic accident. The day her dream of walking on her own vanished.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "sasaki",
    name: "Roki Sasaki",
    name_en: "佐々木 朗希",
    nationality: "Japan",
    birthplace: "Rikuzentakata, Iwate Prefecture",
    birth_date: "November 3, 2001",
    age: 24,
    sport: "Baseball",
    family: "Mother (Yoko), older brother, younger brother.",
    upbringing: "Lost his father and grandparents in the Great East Japan Earthquake. The tsunami took his home, but continuing to play baseball gave his family strength.",
    main_quote: "Baseball is how I repay the people who supported me.",
    sub_quote: "The time I can't pitch is preparation — letting my body grow bigger and stronger.",
    achievements: ["Perfect game (world record 13 consecutive strikeouts)", "WBC champion"],
    injury_detail: "Repeated setbacks due to the fragility of growing bones and recurring tightness in his right arm.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "kimura_saori",
    name: "Saori Kimura",
    name_en: "木村 沙織",
    nationality: "Japan",
    birthplace: "Tokyo (raised in Saitama Prefecture)",
    birth_date: "August 19, 1986",
    age: 39,
    sport: "Volleyball",
    family: "Husband, children, parents, younger sister.",
    upbringing: "A versatile hitter capable of placing any set, she was thrust into the spotlight as the face of the Japanese national team and carried its weight from a young age.",
    main_quote: "Volleyball is about connecting everyone together. I got stronger the moment I realized it wasn't all on my shoulders.",
    sub_quote: "I broke my fingers, but my spirit never broke.",
    achievements: ["2012 London Olympics bronze medal", "Four consecutive Olympic appearances"],
    injury_detail: "Years of knee and back pain, fractured fingers. Compounded by the mental exhaustion of serving as team captain.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "takahashi_naoko",
    name: "Naoko Takahashi",
    name_en: "高橋 尚子",
    nationality: "Japan",
    birthplace: "Gifu, Gifu Prefecture",
    birth_date: "May 19, 1972",
    age: 53,
    sport: "Marathon",
    family: "Parents.",
    upbringing: "A girl who purely loved to run. Under Coach Koide's philosophy of 'coaching through praise,' she blossomed into a world-class endurance runner with an infectious positivity.",
    main_quote: "Enjoying what you do is always the shortest path to success.",
    sub_quote: "When plantar fasciitis kept me from running, I trained every muscle except the ones on the soles of my feet harder than anyone in Japan.",
    achievements: ["2000 Sydney Olympics gold medal (first for a Japanese woman in track & field)", "World record holder"],
    injury_detail: "Plantar fasciitis and knee injuries after the Olympics. Every step sent searing pain through her body.",
    image_url: null,
    comeback_status: "retired",
  },
  {
    id: "oe",
    name: "Hikaru Oe",
    name_en: "大江 光",
    nationality: "Japan",
    birthplace: "Toyama, Toyama Prefecture",
    birth_date: "August 3, 1995",
    age: 30,
    sport: "Snowboard",
    family: "Parents.",
    upbringing: "Immersed in snow-covered mountains from a young age, she grew into one of Japan's top female halfpipe technicians.",
    main_quote: "The fear of riding was nothing compared to the loneliness of not being able to ride at all.",
    sub_quote: "Rehab is like reassembling your muscles piece by piece, like a puzzle.",
    achievements: ["Youth Olympics gold medal", "X Games finalist"],
    injury_detail: "Repeated ACL tears in both knees — the worst possible injury for a snowboarder.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "taniguchi",
    name: "Reia Taniguchi",
    name_en: "谷口 令亜",
    nationality: "Japan",
    birthplace: "Shiga Prefecture",
    birth_date: "Unknown",
    age: 25,
    sport: "Para Snowboard",
    family: "Parents.",
    upbringing: "Fell in love with snowboarding at a young age.",
    main_quote: "My disability is just one part of who I am. On the board, we're all the same.",
    sub_quote: "If you fall down and get back up, it's not a failure.",
    achievements: ["2022 Beijing Paralympics competitor"],
    injury_detail: "A congenital functional impairment in the left foot. Additionally, a major injury sustained during competition.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "ikezaki",
    name: "Daisuke Ikezaki",
    name_en: "池崎 大輔",
    nationality: "Japan",
    birthplace: "Hakodate, Hokkaido",
    birth_date: "January 23, 1978",
    age: 48,
    sport: "Wheelchair Rugby",
    family: "Wife, children.",
    upbringing: "Diagnosed with Charcot-Marie-Tooth disease as a child. As his hands and feet gradually lost strength, he transitioned from basketball to rugby.",
    main_quote: "Rugby is a combat sport. The impact that shatters a wheelchair is proof that I'm alive.",
    sub_quote: "Even as the disease takes away more of my body, I'll train the parts that remain ten times harder.",
    achievements: ["2016 & 2021 Paralympic bronze medals", "2024 Paris Paralympics gold medal"],
    injury_detail: "A progressive neuromuscular disease. Living with the constant fear of losing more grip strength and leg sensation year by year. Additional injuries from brutal on-court collisions.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "kobayashi",
    name: "Ryoyu Kobayashi",
    name_en: "小林 陵侑",
    nationality: "Japan",
    birthplace: "Hachimantai, Iwate Prefecture",
    birth_date: "November 8, 1996",
    age: 29,
    sport: "Ski Jumping",
    family: "All four siblings are ski jumpers.",
    upbringing: "Raised in the nature of Iwate, he idolized Noriaki Kasai and joined Team Tsuchiya Home. The legend personally passed down the 'secrets of flight.'",
    main_quote: "Have fun and you win. There's nothing better than flying through the air.",
    sub_quote: "Going through a terrible slump taught me the patience to wait for the right wind.",
    achievements: ["2022 Beijing Olympics gold medal", "Two-time FIS World Cup overall champion"],
    injury_detail: "Knee injuries in his early career and a psychological slump when results stagnated. He was dogged by the label: 'talented but mentally fragile.'",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "suzuki_takayuki",
    name: "Takayuki Suzuki",
    name_en: "鈴木 孝幸",
    nationality: "Japan",
    birthplace: "Hamamatsu, Shizuoka Prefecture",
    birth_date: "January 23, 1987",
    age: 39,
    sport: "Para Swimming",
    family: "Wife (British), parents.",
    upbringing: "Despite severe limb deficiencies, he was an energetic boy who threw himself into every challenge.",
    main_quote: "Rather than searching for what I'm missing, I focus on how to use what I have.",
    sub_quote: "There were 13 years when I couldn't win gold. That time made me a real athlete.",
    achievements: ["Medals at five consecutive Paralympics", "2021 & 2024 gold medals"],
    injury_detail: "Limb deficiencies in all four extremities. Compounded by years of shoulder strain from competition and the frustration of a 13-year gold medal drought.",
    image_url: null,
    comeback_status: "completed_success",
  },
  {
    id: "otaki",
    name: "Hideji Otaki",
    name_en: "大滝 秀治",
    nationality: "Japan",
    birthplace: "Tokyo",
    birth_date: "Deceased (age 87)",
    age: 87,
    sport: "Kyudo / Theater (Spiritual Athlete)",
    family: "Family.",
    upbringing: "Survived the turbulence of pre-war and wartime Japan. In the barren postwar era, he uplifted people through the power of culture and the arts.",
    main_quote: "One step at a time — even if you have to crawl, that is the true path.",
    sub_quote: "It is in the moment of failure that your true self reveals itself.",
    achievements: ["Extraordinary expressiveness as an actor", "Enduring contributions to Japanese culture"],
    injury_detail: "Wartime conscription followed by postwar famine and lung disease. Years of obscurity as a struggling artist waiting for his breakthrough.",
    image_url: null,
    comeback_status: "retired",
  },
];
